## Premier test de modèle StanfordNLP


### Petite installation necessaire pour l'utilisation du package
https://www.analyticsvidhya.com/blog/2019/02/stanfordnlp-nlp-library-python/

In [1]:
import pandas as pd
import stanfordnlp

In [56]:
# Import le fichier XML
import xml.etree.ElementTree as ET
tree = ET.parse('Lyric_song.xml')
root = tree.getroot()
xmlstr = ET.tostring(root, encoding='utf8', method='xml')
# all items data
print('Expertise Data:')
music_style = []
corpus_list = []
i=0
j=0
for elem in root:
    print(j)
    print(elem.attrib)
    music_style.append(elem.attrib["style"])
   
    j = j+1
    text_test = ""
    for subelem in elem:
        #print(subelem.artist)
        if subelem.text is not None:
            text_test = text_test + subelem.text
            print(subelem.text)
    corpus_list.append(text_test)

Expertise Data:
0
{'artist': 'Julien Doré', 'duree': '', 'genre': '', 'name': 'Paris-Seychelles', 'style': 'Pop'}

Te sourire dehors à Angoulême
Un chasse-spleen Melchior Paris-Seychelles
Découvrir ton corps depuis la scène
Du sombre décor Lucrèce est reine

On s'était dit des choses
Que l'on ne tiendra pas
Le temps que l'eau se pose
Sur nos ronces lilas

Le soleil s'endort sur Seychelles
Le sable et l'aurore, fleur de sel
Attends-moi je sors, de l'Île aux cerfs
L'orage est de l'or pour se perdre
 (x4)
I need you so, oh oh
I won't let you go, woh oh

Souffrir la mort pour te plaire
Défendre nos torts et puis se taire
Le désir encore pour l'hiver
Un chaos d'efforts sur Saint Hilaire

On s'était dit des choses
Que l'on ne tiendra pas
Le temps que l'on se pose
Sur nos lauriers mayas

On s'était dit des choses...
1
{'artist': 'Fréro Delavega', 'duree': '', 'genre': '', 'name': 'Le chant des sirènes', 'style': 'Pop'}

Enfants des parcs, gamins des plages
Le vent menace les châteaux de sable

Pour un regard en croix c'est la fin
9
{'artist': 'Black M', 'duree': '', 'genre': '', 'name': 'Je suis chez moi', 'style': 'Pop'}

Tout le monde me regarde
A travers mon innocence je pense qu'ils me charment
Ma maîtresse d'école m'a dit que j'étais chez moi
Mais mon papa lui pourtant se méfie d'elle, est-elle fidèle ?
La France est belle
Mais elle me regarde de haut comme la Tour Eiffel
Mes parents m'ont pas mis au monde pour toucher les aides
J'ai vu que Marion m'a twitté d'quoi elle se mêle ? Je sais qu'elle m'aime

Je suis français
Ils veulent pas que Marianne soit ma fiancée
Peut-être parce qu'ils me trouvent trop foncé
Laisse moi juste l'inviter à danser, j'vais l'ambiancer
Je suis français
Ils veulent pas que Marianne soit ma fiancée
Peut-être parce qu'ils me trouvent trop foncé
Laisse moi juste l'inviter à danser, j'vais l'ambiancer

J'paye mes impôts moi
J'pensais pas qu'l'amour pouvait être un combat
A la base j'voulais juste lui rendre un hommage
J'suis tiraillé comme mon gr

(La la la la la la)
14
{'artist': 'Kendji Girac', 'duree': '', 'genre': '', 'name': 'Maria Maria', 'style': 'Pop'}

Et ça r'commence
J’lui parle d'amour que dans un silence
Mes yeux savourent, son galbe s'déhanche
Entre méfiance et ce qu'elle en pense
Je prends ses courbes et j’augmente mes chances
J'me d'mande c'qu'on fera comme folie
Des crampes, des torticolis
J'veux entendre toute sa mélodie
On y passera toute la nuit
Et comme toujours, ça recommence
Dis-moi, dis-moi, dis-moi

Maria, Maria, Maria
Dis-moi c'que tu veux faire dans le noir
Maria, Maria, Maria
Dis-moi c'que tu veux faire dans le noir

C'est exceptionnel
Elle a peur de l'avion mais veut toujours le septième ciel
Dire ce que j’ressens, non ça n’vaut pas la peine
Elle m’fait des scènes huit jours par semaine
En filature j'ai pris ses sentiments
En miniature j'ai pris des photos d'elle
J’fais l’meilleur, elle ne fait que son possible
J’dis “à tout à l'heure”, elle m’dit “j’s’rai pas là”
Dans son cœur, y'a d’quoi faire des 

Et puis seulement quand c’est fini
19
{'artist': 'Stromae', 'duree': '', 'genre': '', 'name': 'Papaoutai', 'style': 'Pop'}

Dites-moi d'où il vient
Enfin je saurai où je vais
Maman dit que lorsqu'on cherche bien
On finit toujours par trouver
Elle dit qu'il n'est jamais très loin
Qu'il part très souvent travailler
Maman dit "travailler c'est bien"
Bien mieux qu'être mal accompagné
Pas vrai ?

Où est ton papa ?
Dis-moi où est ton papa ?
Sans même devoir lui parler
Il sait ce qui ne va pas
Ah sacré papa
Dis-moi où es-tu caché ?
Ça doit, faire au moins mille fois que j'ai
Compté mes doigts
Hey !

Où t'es, papaoutai?
Où t'es, papaoutai?
Où t'es, papaoutai?
Où t'es, où t'es où, papaoutai ?
Où t'es, papaoutai ?
Où t'es, papaoutai ?
Où t'es, papaoutai ?
Où t'es, où t'es où, papaoutai ?
Où t'es
Où t'es...

Quoi, qu'on y croit ou pas
Y aura bien un jour où on n'y croira plus
Un jour ou l'autre on sera tous papa
Et d'un jour à l'autre on aura disparu
Serons-nous détestables ?
Serons-nous admirabl

À l'ombre de ma plume

Ma beauté repose toi
Ma beauté repose toi
J'ai les épaules pour ça
J'ai les épaules pour ça
Ma beauté repose toi
J'ai les épaules pour ça

J'ai tout gâché, maintenant tu m'abandonnes
J'ai tout gâché, maintenant tu m'abandonnes
J'l'ai mérité, dans les rues je vagabonde
J'l'ai mérité, dans les rues je vagabonde
J'ai tout gâché, cette fois sera la bonne
Fais moi confiance, je changerai la donne
J'ai tout gâché, maintenant tu m'abandonnes
J'l'ai mérité, dans les rues je vagabonde

Laisse moi devenir meilleur
Laisse moi réparer mes erreurs
Pince moi, pince moi, oui pince moi je rêve
Pince moi, pince moi, oui pince moi je rêve
Laisse moi devenir meilleur
Laisse moi réparer mes erreurs
Pince moi, pince moi, oui pince moi je rêve
Pince moi, pince moi, oui pince moi je rêve
25
{'artist': 'Bigflo & Oli', 'duree': '', 'genre': '', 'name': 'Dommage', 'style': 'Pop'}

Louis prend son bus, comme tous les matins
Il croisa cette même fille, avec son doux parfum
Qu'elle vienne lu

Les gens me disaient : "Méfie-toi d'cette fille-là"
29
{'artist': 'Gims', 'duree': '', 'genre': '', 'name': 'J’me tire', 'style': 'Pop'}

J'me tire, me demande pas pourquoi j'suis parti sans motif
Parfois je sens mon cœur qui s'endurcit
C'est triste à dire mais plus rien n'm'attriste
Laisse-moi partir loin d'ici
Pour garder l'sourire, je me disais qu'y'a pire
Si c'est comme ça, bah fuck la vie d'artiste
Je sais qu'ça fait cliché d'dire qu'on est pris pour cible
Mais j'veux l'dire juste pour la rime

J'me tire dans un endroit où j'serai pas l'suspect
Après j'vais changer d'nom comme Cassius Clay
Un endroit où j'aurai plus besoin d'prendre le mic'
Un endroit où tout l'monde s'en tape de ma life

J'me tire, me demande pas pourquoi j'suis parti sans motif
Parfois je sens mon cœur qui s'endurcit
C'est triste à dire mais plus rien n'm'attriste
Laisse-moi partir loin d'ici
Pour garder l'sourire, je me disais qu'y'a pire
Si c'est comme ça, bah fuck la vie d'artiste
Je sais qu'ça fait cliché d'

J'attends plutôt mon tour

Mais c'est pas pour autant qu'il faut
Qu'on s'attache et qu'on s'empoisonne
Avec une flèche qui nous illusionne
Faut pas
Qu'on s'attache et qu'on s'emprisonne
Mais rien n'empêche que l'on s'abandonne
Non

On laisse rien
Le quotidien ça me tue, ça me tient
Ça me fait mal
Rien de plus normal
Mais tu t'enfiles
Dans la file
Il faut pas que tu dépasses
À chaque fois que tu resquilles
Mais t'es qui ?
T'es pas normal

On s'attache et on s'empoisonne
Avec une flèche qui nous illusionne
Faut pas, non
Qu'on s'attache et qu'on s'emprisonne
Mais rien n'empêche que l'on s'abandonne
Non
Faut pas
Qu'on s'attache et qu'on s'empoisonne
Avec une flèche qui nous illusionne
Faut pas non
Qu'on s'attache et qu'on s'emprisonne
Mais rien n'empêche que l'on s'abandonne
Non, non

C'est beau l'amour
J'attend mon tour
34
{'artist': 'Christophe Maé', 'duree': '', 'genre': '', 'name': 'Belle Demoiselle ', 'style': 'Pop'}

Du fond de ma rue
Une silhouette comme un bruit aigu
Se rapproche à

Yeah

À cause de toi, j’me suis écarté d’mes amis
J’pense tellement à toi que j’en dors plus la nuit
À cause de toi, je n’vois plus aucune autre fille
J’sais pas, j’ai l’impression qu’elle n’t’arrive pas à la cheville
C’est bizarre mais quand t’es pas là, j’crois que tout m’ennuie
J’pense tellement à toi que j’en dors plus la nuit
À cause de toi, je n’vois plus aucune autre fille
J’sais pas, j’ai l’impression qu’elle n’t’arrive pas à la cheville

Ah, dis-moi, dis-moi comment on fait, comment on fait, comment on fait, comment on fait
Dis-moi comment on fait, comment on fait, comment on fait
Ah, dis-moi, dis-moi comment on fait, comment on fait, comment on fait, comment on fait
Dis-moi comment on fait, comment on fait, comment on fait

Tu sais, les filles, c’est pas c’qui manque, si j’veux, j’peux en avoir
Mais là, c’que j’ressens pour toi, j’t’avoue, c’est la première fois
J’ai tout fait pour me voiler la face, j’y arrive pas
Toi à mes côtés dans mon avenir, j’te jure, je nous vois
Ne n

Avec une fille à la garçonne
Dieu veillait sur lui sans doute
Car bien que l'on n'y vit goutte
Le fêtard
Chaque soir
Dans le noir
Retrouvait l'avenue Mozart
Mais par un beau soir d'automne
Il ingurgita par tonnes
Du solide
Des liquides
Du fluide
Qui lui gonflèrent fortement le bide
Il eut l'envie importune
D'arroser sous la pleine lune
L' réverbère
Solitaire
Qui éclaire
Le Ministère de la Guerre
Mais faut croire qu'il voyait trouble
Plutôt à moitié que double
Car au lieu du luminaire
Il éteignit le factionnaire
Qui surveillait le Ministère
45
{'artist': 'Henri Salvador', 'duree': '', 'genre': '', 'name': 'Le Taxi', 'style': 'Pop'}
Je sais que tu sais que je t'aime
N'est-ce pas que tu le sais
Jamais je ne t'en ai fait l'aveu
Mais je sais que tu sais tout quand même
Car tu sais lire dans mes yeux
Mon cœur est pour moi sans mystère
N'est-ce pas que c'est bien vrai tu suis tous mes rêves pas à pas
Tu lis en moi beaucoup mieux qu'en toi-même
Car tu m'aimes... et tu ne le sais pas
Quand je s

J’vois le virage et je dérape

Folie (really, really), han
Hier soir, j’ai fait des folies (really, really), yeah
La bitch était sous molly, j’dois r’monter la coline
Elle est montée dans mon bolide (really, really)
Oh, c’est des folies (really, really)
59
{'artist': 'dinos', 'duree': '', 'genre': '', 'name': 'les pleurs du mal', 'style': 'Rap'}

Jules...
On s'déteste et on s'aime, de façon calamiteuse
Car chez nous le ciel est terne comme...
(Laisse tourner un peu le son)

On s'déteste et on s'aime, de façon calamiteuse
Car chez nous le ciel est terne comme une station de la ligne 2
Ils comprennent pas nos vies parce qu'ils savent pas c'qu'on a vécu
On pourrait faire de faux sourires mais même ça on y arrive plus
Dis aux racistes qu'on les baise
Dis à l'huissier qu'on bougera pas
Qu'il retourne se branler sur des catalogues Conforama
J'ai qu'une équipe c'est ma famille, j'm'en bas les couilles de c'que l'on dit
J'suis venu au monde sans label, sans éditeur, sans maison de disques
Rien

Au point de chialer toute la nuit sur un vieux son de rap français ?

J'ai pas fait d'études, j'emmerde tes politiques, j'ai pas fait HEC
J'ai pas b'soin d'ça pour m'exprimer quand j'vois des pauvres sur la chaussée
J'connais les tafs de merde, les potes qui partent, le shit dans la chaussette
J'me suis longtemps d'mandé si j'pouvais faire quelque-chose mais, là, je sais
Non, j'ai pas fait l'ENA ni Sciences Po, j'ai pas fait HEC
J'ai pas b'soin d'ça pour m'exprimer quand j'vois des pauvres sur la chaussée
J'connais les tafs de merde, les potes qui partent, le shit dans la chaussette
J'me suis longtemps d'mandé...

J'viens d'un monde où même les morts sont à vendre, j'avance car l'avenir m'attire
Et j'réponds aux questions du morceau d'avant par l'affirmative
Personne pour alléger nos peines, tu f'rais quoi à notre place ?
Y'a des choses qu'on doit faire seul, personne pourra lécher nos plaies
À notre place, parcourir la ville avec mes chats crevés
Partager chaque grain, noyer notre cha

Trois heures en bas d'chez toi, il m'faut ta peau

Que du midi-minuit pour le bénéfice, on les a jamais vu, ils s'inventent des vies
J'ai vu les vrais quand y avait pénurie, j'ai fait déménager tous mes ennemis
J'suis dans l'noir mais j'ai billets verts, j'ai kilos calés dans l'appuie-tête
Elle croit que, en la baisant, j'lui ferai goûter à la vie d'rêve

On fait pas la guerre avec un 6.35, on est 36 contre 5
J'ai des grands frères, grands sins-c mais j'les appelle pas quand y a drah
40 mètres, la frappe est cadrée, arrivage de frappe y a 40 mètres, un seul mort refroidit 40 mecs
La balle est partie, elle est cadrée (elle est partie, elle est cadrée)
J'ai la 0.9, j'ai l'AR, avec mon 9, on fait la paire, j'sors plus en BGV, avenue Ampère
Sevran, BDT, qui veut me faire ? J'ai pas l'temps pour plaire à d'autres fils de pute
Ils sont pas solides, ils vont porter plainte, minuit, j'vais payer l'bosseur et le PU
J'ai rencontré mes peurs et vaincu mes craintes, j'ai des amis en moins et des r

Ton style est trop bof (hey) Moi hamdoulah ca va (hey)

Ze-ze-ze-ze-ze-ze, Ze-ze-ze-ze-ze-ze
Ze-ze-ze-ze-ze-ze, Ze-ze-ze-ze-zehefyu
A-a-a-a-a-a, A-a-a-a-a-a
A-a-a-a-a-a, A-a-a-a-acide
Ze-ze-ze-ze-ze-ze, Ze-ze-ze-ze-ze-ze
Ze-ze-ze-ze-ze-ze, Ze-ze-ze-ze-zehefyu
A-a-a-a-a-a, A-a-a-a-a-a
A-a-a-a-a-a, A-a-a-a-acide

J'abuse come un junky (hey) Zehef n'est pas funky (hey)
La merde dans ton bagguy (hey) L'horreur, moi c'est Chucky (hey)
Flow trop barraqué J'mange tout comme les harkis (hey)
J'glisse comme au ski (hey) Au top comme cherokee (hey)
Lève tôt comme les frosties (hey) Hallal mange pas de chee-eese (hey)
Toujours le filet au fii-iish (hey) Au MacDo bitches (hey)
J'contrôle mon bi-iz (hey) Même en periode de cri-ise (hey)
La lame j'égui-ise (hey) Le ter-ter j'maîtri-ise (hey)
Moi j'fais pas la bi-ise (hey) Je baise le show-bi-iz (hey)
J'te l'dis en toute franchi-ise (hey) Ton flow il pu la pi-isse (hey)
J'défonce comme une perqui-ise (hey) Des keufs dans ta té-éss (hey)
T'as retrouvé

Il m'appelle "mon fils" quand il frappe à ma porte, ton papa m'adore

Quelques tics de bandit
Des mimiques de voyous
Chiens d'la casse
Mais l'esprit est gentil
78
{'artist': 'flynt', 'duree': '', 'genre': '', 'name': "j'eclaire ma ville", 'style': 'Rap'}
79
{'artist': 'a2h', 'duree': '', 'genre': '', 'name': 'on charbonne', 'style': 'Rap'}

Han, oui, tu m'as pris pour un autre
On n'est pas là pour s'branler, pas là pour faire le beau
Attends, je cuisine la dope
J'suis dans le stud', j'te parle de tubes, pas de coke
C'est vrai, ici, c'est la merde, renoi
Y'a pas grand-chose à faire, le soir
Y'a de la verte dans les cônes
Mais on charbonne, ramène le blé pour les mômes

On charbonne, on charbonne
Ramène le blé pour les mômes
On charbonne, on charbonne
Ramène le blé pour les mômes
On charbonne, on charbonne
Ramène le blé pour les mômes
Ramène le blé pour les...
Ramène le blé pour les mômes

J'vais faire monter ma clique, ouais, j'te marche sur la tête
J'passe prendre R, il est p't-être à 

Si j'veux, j'te donne de ma part, frère, à la base, j'suis qu'un gros bâtard

Me parlent mal, vous voulez quoi ?
Pour rien, on s'emporte, on s'envole vers la mort
Chargeur plein d'balles, la vie est belle
Maman ne pleure pas, j'ai fait ça pour l'argent
Me parlent mal, vous voulez quoi ?
Pour rien, on s'emporte, on s'envole vers la mort
Chargeur plein d'balles, la vie est belle
Maman ne pleure pas, j'ai fait ça pour l'argent
83
{'artist': 'ateyaba', 'duree': '', 'genre': '', 'name': "2014 à l'infini", 'style': 'Rap'}
84
{'artist': 'niro', 'duree': '', 'genre': '', 'name': 'fort et vivant', 'style': 'Rap'}

Ambition Music

Tu fais rien d'ta vie mais, tu donnes ton avis comme un mec de Twitter
Quelques RT, ton heure de gloire s’arrête ce soir à dix-huit heures
Pas la peine de m'demander ce que j'en pense du rap game, moi,  j'suis pas auditeur
Réveille pas l'eau qui dort, j'vais nehess au mitard, allumez vos leader, retrouvez vos videurs
J'vais pas passer ma vie à manquer mes rêves, j'ai a

Joffrey, Joffrey, Joffrey, Joffrey, Joffrey

M'regarde pas à travers, qu'est-ce qu'il s'passe ? J'fais des doigts derrière l'plexiglas
J'rappelle jamais, ça m'déshydrate ; me demande pas d'feat, fume des chichas
Puis prends la photo avec la fumée, bats les couilles d'être affublé
Comme l'année dernière, adulez : avé Joffrey, l'cavu net
Fais le fou, j'peux t'acculer, plus calé qu'un mec à lunettes
C'est mécanique, je fais qu'allumer, troque la paix, pas les calumets
J'ai la fourche et l'allumette, j'ai la frousse et la lumière
Tu fais le boug'zer qu'a du flair, mais t'avoues qu'elle t'a dupé
Tu verras pas les backstages, saleté, 'té-ma' ta sale tête
On dirait une face B sur iPhone 3G (3G, 3G, 3G, j'crois j'ai 3g)
J'crache des poèmes comme une saleté d'bohèmien
J'parfais mon dessein, tu caresses nos raisins
Sois contre moi, je ferai genre t'as raison pour qu'tu penses que t'es chaud puis qu'on devienne poto
Que j't'invite au 'Do-Mac', que j'mette de la ricine dans ton foutu Big Mac
C'est

Voilà pourquoi certains de mes frères face au succès ont le sang chaud

Pourquoi le ciel est bleu, pourquoi l'on vit mieux à deux
Pourquoi l'argent et le pouvoir rendent les amis dangereux
La jalousie ? L'hypocrisie ?
Quand elle choisit son camp, fout l'camp

Croyant que la galère nous ralliait sous une bannière (x2)

J'ai bossé avec des personnes en qui j'avais confiance
Pendant 4 années les choses allaient dans le bon sens
Voyages, restaurants, loisirs choisir
Entre le meilleur et le meilleur pour mon avenir
Mon avenir, la musique
Mais pour eux c'était plus pour le fric
Hip Hop de luxe à 50 keuss le sweat ils m'ont aveuglé
Par des avantages qui m'ont déréglé, m'ont rendu cinglé
Contre un mur m'épingler. Certains voulaient m'étrangler
Ça n'a pas tardé, le 20 mars 97 ça a bardé
Les mêmes soi-disant amis dévoués
Pour être près de moi, étaient loin de moi
Lorsque je criais "aidez-moi"
Mais non, l'argent te rend sourd, aveugle et muet
Impossible de bouger même si ton pote se fait tuer
Tu 

Le laisse pas chercher ailleurs, l'amour qui devrait y avoir dans tes yeux

Laisse pas traîner ton fils
Si tu ne veux pas qu'il glisse, qu'il te ramène du vice
Laisse pas traîner ton fils
Si tu veux pas qu'il glisse

Putain, c'est en me disant :"J'ai jamais demandé à t'avoir !"
C'est avec ces formules, trop saoulées, enfin faut croire
Que mon père a contribué à me lier avec la rue
J'ai eu l'illusion de trouver mieux, j'ai vu
Ce qu'un gamin de quatorze ans, avec le décalage de l'âge
Peut entrevoir, c'était comme un mirage
Plus d'interdit, juste avoir les dents assez longues
Pour croquer la vie, profiter de tout ce qui tombe
La rue a su me prendre car elle me faisait confiance
Chose qui avec mon père était comme de la nuisance
Aucun d'entre nous n'a voulu recoller les morceaux
Toute tentative nous montrait qu'on avait vraiment trop d'ego
Mon père n'était pas chanteur, il aimait les sales rengaines
Surtout celles qui vous tapent comme un grand coup de surin en pleine poitrine
Croyant la j

Cette putain de pierre à l'édifice

J'suis un tantinet entêté
J'ai déjà plus rien à fêter
Tant pis si on s'était
Menti
Les intempéries vont m'aider
J'ai déjà presque oublié
Tant pis si on s'aimait
Tant pis
Oh, tant pis
Tant pis, (tant pis)
Tant pis, tant pis, (tant pis)
102
{'artist': 'sopico', 'duree': '', 'genre': '', 'name': 'le hasard ou la chance', 'style': 'Rap'}

Enfoiré t'es pété tu cons grave, tu connais bien l'effet du bon sky
Si j'ai des jetons j'crache, Béné veut qu'on s'capte
Mon bébé veut qu'on s'capte
J'suis à Paris, situe l'fief
Dojo volant si tu viens par ici, tu m'cherches
À des années de tes plans
Regarde-moi faire, j'vais pas parler, jeter d'l'encre
J'pourrais l'cracher en toutes langues
Olé, j'suis d'vant l'brasier en coupe-vent
J'vais m'en aller en tournant en boucle dans tes oreilles comme Harley en doublant
Comme un grand j'ai c't'air
On s'voit vingt-huit jours plus tard à Manchester
J'ai cuisiné un remède à lancer, j'teste
Comme un zombie, ton fiston va manger 

C'est là où y'a plein d'histoires : écoute bien

Regarde là où j'vis
Ok c'est pas Auschwitz
Mais c'est auch', vite faut que j'trouve autre chose, fils
T'façon j'vais m'casser : c'est c'qu'a dit l'huissier
Oui j'sais : il peut pas m'virer en hiver, mais dis-lui ça
Il s'est pointé ici fissa, pour l'torturer j'ai pissé dans l'escalier
Pensant que l'odeur l'tuerait : qui sait ?
Et puis ça lui a mis la puce à l'oreille
Tant qu'ils t'ont pas pris c'que tu n'as pas, ils n'dorment pas tranquille
Ils m'ont coupé l'chauffage et l'téléphone
J'suis circoncis, sinon ils essaieraient d'me la couper et comme
Et comme ici les Droits d'l'Homme, c'est payer des sommes folles
Ils ont la rage, les cainfs ont les allocs et pas qu'une seule femme
Un p'tit m'dit : "T'inquiète, on s'en sort sans prof
Mec, on aura l'bac dès qu'l'ascenseur sera propre"
Brahim me dit : "Y'a pas d'école, y'a l'Aïd"
Et là il m'dit : "Wallaye, là où on vit c'est pas une life"
J'demande son âge il m'ment, il m'dit seize ans
Eh mets 

Paniquez pas c'est que du pe-ra, Bagneux, Sevran que d-la peu-fra

92, 93, Bagneux, Sevran (Que D'la peu-fra)
Pecho chez nous t'aura (Que D'la peu-fra)
Leggins, Chicha, Jordan, Tn, tel-hô (Que D'la peu-fra)
Sultan et Ixzo ce n'est (Que D'la peu-fra)
Pourquoi tu regardes dans le rétro, on est déjà à bord de nos vaisseau
On s'en bat les couilles de la 4G, nous on contrôle déjà le réseau
Le mental est bien d'acier, on passe pas les détecteurs de métaux
Les colons sont dépassé, indomptable comme samuel Eto'o
112
{'artist': 'scred connexion', 'duree': '', 'genre': '', 'name': 'partis de rien', 'style': 'Rap'}

Partis de rien, on arrive à ce qu’on vise
Et vu qu’on apprend rien qui nous aide, c’est souvent rien, ce qu’on vise
Ils disent souvent qu’on est des bons à rien
Et il suffit d’un rien pour qu’on y croit quoi que t’en dises !
On va pas perdre notre temps à moisir ici, quoi que t’en dises !
Partis de rien, on va trouver la sortie, quoi que t’en dises !
C'est pour tous ceux qui ont pour 

La femme des autres
On irait chasser
Dans les beaux quartiers
Et dans l'ascenseur
On f'rait l'joli cœur
Et tout là-haut, là-haut
Tout là-haut, là-haut
Venue d'Amérique
Y aurait d'la musique
119
{'artist': 'Serge Gainsbourg', 'duree': '', 'genre': '', 'name': "L'alcool", 'style': 'Jazz'}
Mes illusions donnent sur la cour
Des horizons j'en ai pas lourd
Quand j'ai bossé toute la journée
Il ne me reste plus pour rêver
Qu'les fleurs horribles de ma chambre
Mes illusions donnent sur la cour
J'ai mis une croix sur mes amours
Les p'tites pépées pour les toucher
Faut d'abord les allonger
Sinon c'est froid comme en décembre
Quand le soir venu j'm'en reviens du chantier
Après mille peines et le corps harassé
J'ai le regard morne et les mains dégueulasses
De quoi inciter les belles à faire la grimace
Bien sûr y a des filles de joies sur le retour
Celles qui mâchent le chewing-gum pendant l'amour
Mais que trouverais-je dans leur corps meurtri
Sinon qu'indifférence et mélancolie
Dans mes frusques co

De toi et moi avant l'hiver
Je veux une grande parade
Une retraite aux flambeaux
Des majorettes, une fontaine
Je veux un drapeau
Une petite mascarade
Un carnaval à Bornéo
Nous deux, un tango à trois temps
Je veux, encore une fois seulement
Un tour de manège
Des feux de joies avant qu'il neige
Des phares, des lumières
De toi et moi avant l'hiver
129
{'artist': 'Henri Salvador', 'duree': '', 'genre': '', 'name': 'Vagabond', 'style': 'Jazz'}
Je suis né sous un ciel de traîne
Entre Hambourg et Cuba
Depuis je me promène
Sur mon nuage à moi
Là où le vent me mène
J'ai entendu tant de sirènes chanter ici et là
Que j'ai eu de la peine
A filer toujours droit
Que j'ai eu de la peine
Tous les vagabonds vagabondent
Et croisent un jour leur chance
La terre n'est pas si ronde
Tous les vagabonds vagabondent
Abondent dans mon sens
Sur la même d'ondes
Je me suis mis en quarantaine
Déjà au moins deux fois
Loin des soirées mondaines
Qui filent à la coda
Pour jouer les mêmes rengaines
Les chansons les plus

De t'aimer follement nuit et jour
Mais quand tu n'est pas là je pense encore a toi
Car je sais que tu reviendras et personne au monde ne m'empêchera
De t'aimer follement mon amour
De t'aimer follement nuit et jour
138
{'artist': 'Johnny hallyday', 'duree': '', 'genre': '', 'name': 'Souvenirs, souvenirs', 'style': 'Rock'}
Souvenirs, souvenirs
Je vous retrouve dans mon cœur
Et vous faites refleurir
Tous mes rêves de bonheur
Je me souviens d'un soir de danse
Joue contre joue
Des rendez-vous de nos vacances
Quand nous faisions les fous
Souvenirs, souvenirs
De nos beaux jours de l'été
Lorsque nous partions cueillir
Mille fleurs, mille baisers
Et pour mieux garder dans ma tête
Les joies de la belle saison
Souvenirs, souvenirs
Il nous reste nos chansons
Souvenirs, souvenirs
Quelque part dans le matin
Où le soleil semblait rire
Tout le long de nos chemins
Nous n'avions au fond de nos poches
Qu'un peu d'espoir
Mais nous partions comme Gavroche
Le cœur assez bavard
Souvenirs, souvenirs
Vous reve

{au Refrain, x2}
155
{'artist': 'Johnny hallyday', 'duree': '', 'genre': '', 'name': 'Toi qui regrettes', 'style': 'Rock'}
Oh, toi qui regrettes
De m'avoir fait souffrir
Oh, toi qui regrettes
Nos anciens souvenirs
Oh, toi qui regrettes
Aujourd'hui ton départ
Oui, toi qui regrettes
Pourquoi viens-tu si tard ?
Je t'aimais comme un fou
Tu m'as fait les cent coups
Tu as griffé mon coeur
Tant pis pour toi, ma mie
Pour moi tout est fini
Le temps a su sécher mes pleurs
156
{'artist': 'Johnny hallyday', 'duree': '', 'genre': '', 'name': 'Avec une poignée de terre', 'style': 'Rock'}
Avec une seule poignée de terre
Il a créé le monde
Et quand il eut créé la terre
Tout en faisant sa ronde
Le seigneur jugeant en somme
Qu'il manquait le minimum
Il créa la femme
Et l'amour qu'elle a donné aux hommes
Avec une seule poignée de terre
Il a créé tes lèvres
Et tes deux bras quand ils me serrent
Pour me donner la fièvre
Et je pense à chaque instant
Que celle que j'aime tant
Le seigneur l'a faite
Avec une s

164
{'artist': 'Johnny hallyday', 'duree': '', 'genre': '', 'name': 'Viens danser le twist', 'style': 'Rock'}
Venez les copains
Tapez des mains
On va faire le twist
C'est le nouveau rock
Rien n'y hésite
N'hésitons pas
Faites comme moi
Suivez bien mes pas
Rythme le twist
Donne-moi la main, là
Tu t'y prends bien
Continue comme ça
Un tour autour de moi
Balance encore tes bras
Viens sur mon cœur
Et rythme le twist
Ah, tourne bien
Oui, tourne bien encore
Oui mais en dansant
N'oublie pas, n'oublie pas
Que je suis là
Tout en rythmant le twist
Entre tes bras
Mon cœur bat pour toi
Rythme le twist
Donne-moi la main, là
Tu t'y prends bien
Continue comme ça
Un tour autour de moi
Balance encore tes bras
Viens sur mon cœur
Et rythme le twist
Ah, tournera
Oui, tourne bien encore
Oui mais en dansant
N'oublie pas, n'oublie pas
Que je suis là
Tout en rythmant le twist
C'est ça le twist
Frappe des mains
165
{'artist': 'Johnny hallyday', 'duree': '', 'genre': '', 'name': "Let's Twist Again", 'style': 'Roc

On a rendez-vous en piste
Vous ne pouvez pas résister
Dans vos deux mains vous frapperez
Sur un tempo bien balancé
Croyez-moi, oui, ça va chauffer
182
{'artist': 'Johnny hallyday', 'duree': '', 'genre': '', 'name': 'Hey Baby', 'style': 'Rock'}
Hey, baby
Est-ce que tu veux être mon amie?
Hey, baby
Est-ce que tu veux être mon amie?
Quand je t'ai rencontrée dans la rue
Je m'suis dit que j'n'avais jamais vu
Jamais de ma vie, une fille aussi
Aussi jolie que toi
Que toi
Hey, baby
Est-ce que tu veux être mon amie?
Quelle tête tu faisais
Quand je t'ai abordée
Tu as rougi
Et puis tu t'es sauvée
Juste au moment
Où je te disais
Hey, baby
Est-ce que tu veux être mon amie?
Mais je t'ai couru après
Et je t'ai rattrapée
Toute essoufflée alors tu m'as souri
Et tu m'as dit oui
Quand je t'ai dit
183
{'artist': 'Johnny hallyday', 'duree': '', 'genre': '', 'name': 'Une fille comme toi', 'style': 'Rock'}
Très longtemps, j'ai cherché
Par les rues encombrées de la ville
Tes grands yeux, ta beauté
Et ton allu

Mes amis je vis dans un jardin d'amour
Tomber amoureux d'une rose
Qui a le parfum du lilas
C'est avoir un peu de printemps toujours avec soi
Quand elle est là, c'est insensé
Mon coeur s'enflamme d'un grand bouquet de joie
Mille boutons d'or ont mis dans ses cheveux
L'éclat du soleil merveilleux
Voilà pourquoi oui pourquoi
Mes amis je vis dans un jardin d'amour
Tomber amoureux d'une rose
Qui a le parfum du lilas
C'est avoir un peu de printemps toujours avec soi
Quand elle est là, c'est insensé
Mon coeur s'enflamme d'un grand bouquet de joie
187
{'artist': 'Johnny hallyday', 'duree': '', 'genre': '', 'name': 'Laissez-nous twister ', 'style': 'Rock'}
Vous avez connu le bon temps
Pour nous qui avons vingt ans
Le bon temps c'est maintenant
Et laissez-nous twister
S'agit pas de vous moquer
Arrêtez de nous blâmer
Nous dansons ce qui nous plaît
Et laissez-nous twister
Ouais, twister, twister
A votre tour de danser
Twister, twister
Et laissez-nous twister
On ne vous reproche pas
Le tango ou le 

Il me dit : Wow, wow, ouh, ouh, ouh, wow, wow, ouh, ouh, ouh, wow
217
{'artist': 'Les Chaussettes Noires', 'duree': '', 'genre': '', 'name': 'Oublie-moi', 'style': 'Rock'}
Oublie-moi
Je ne suis pas un garçon fait pour toi
Et si jamais ton cœur s'attache à moi
Tu souffriras, han, han
Han, oublie-moi
Pour un baiser que nous avons cueilli
Je n'ai pas le droit de gâcher ta vie
C'est une folie, han han han han
Moi, tu le sais, je m'en vais au hasard
Je ne connais que les rêves d'un soir
Le lendemain, sans savoir où je vais
Je reprends ma liberté
Oublie-moi
Je ne veux pas te voir pleurer demain
Pour un amour qui ne te promet rien
Que du chagrin, han han chap pa da pa da
Oublie-moi
Je t'ai blessée en te parlant ainsi
Pourtant, un jour tu me diras, mais oui
Un grand merci, han han han han
{Refrain:}
Ne me dis pas que ton cœur est brisé
Sèche tes pleurs et puis viens m'embrasser
{x2:}
Je ne veux pas qu'un beau jour
Toi, tu souffres pour moi
Ouais, ouais, oublie-moi !
Moi, tu le sais, je m'en va

Croyez-moi, les gars
{au Refrain}
Depuis ce jour-là, c'est fou, je ne vis plus
Cette fois, ça y est, je suis bien mordu
Je suis impatient
Tous les soirs, j'attends
L'instant dont j'ai tant rêvé
Pour nous embrasser
{au Refrain}
234
{'artist': 'Les Chaussettes Noires', 'duree': '', 'genre': '', 'name': 'Jezelbel', 'style': 'Rock'}
Jezebel... Jezebel...
Ce démon qui brûlait mon cœur
Cet ange qui séchait mes pleurs
C'était toi, Jezebel, c'était toi
Ces larmes transpercées de joie
Jezebel, c'était toi... Jezebel, c'était toi...
Mais l'amour s'est anéanti
Tout s'est écroulé sur ma vie
Écrasant, piétinant, emportant mon cœur
Jezebel... Mais pour toi
Je ferais le tour de la terre
J'irais jusqu'au fond des enfers
Où es-tu ? Jezebel, où es-tu ?
Les souvenirs que l'on croit fanés
Sont des êtres vivants
Avec des yeux de morts vibrants encore de passé
Mais mon cœur est crevé d'obsession
Il bat en répétant
Tout au fond de moi-même
Ce mot que j'aime
Ton nom...
Jezebel... Jezebel...
235
{'artist': 'Le

Que je t'attends
J’ai tant de projets
Que tu aimerais
Si tu voulais bien comprendre
Pourquoi je les fais
260
{'artist': 'Dick Rivers', 'duree': '', 'genre': '', 'name': 'Rien Que Toi', 'style': 'Rock'}
261
{'artist': 'Dick Rivers', 'duree': '', 'genre': '', 'name': "Quand Je L'Ai Vue Devant Moi", 'style': 'Rock'}
Nous nous voyons pour la première fois
C'est l'impression que j'ai en tous cas
Je suis parti pour un curieux voyage
Dont on ne revient pas
La route défilait devant moi
La radio jouait "Ne me quitte pas"
Puis ce fut comme dans les choses de la vie
Un film au ralenti
Il n'y a plus de souvenirs
Rien pour me retenir
Il n'y a plus de souvenirs
Seulement de l'ennui
Il n'y a plus de souvenirs
Plus de peurs que de désirs
Et quand on s'embrasse
Il n'y a plus la foudre d'hier
Du moins c'est c'que tu m'dis
Désormais ce n'est plus que Jeanne
Et Henri
Plus rien ne m'est vraiment familier
Mais c'est presque mieux je dois l'avouer
On me dit qu'il faut être patient
Mais je n'ai pas le temps
C

Elle n'était pas rentrée, même au petit matin
Même si elle dit qu'elle m'aime
Entre nous c'est fini
Même si elle dit qu'elle m'aime
Entre nous c'est fini
Elle dépense mon argent avec tous mes copains
Me trompe avec eux, ça c'est sûr et bien certain
Jusqu'à présent, c'est vrai, je n' lui avais rien dit
Mais cette fois elle exagère, alors, eh bien, tant pis !
Même si elle dit qu'elle m'aime
Entre nous c'est fini
Même si elle dit qu'elle m'aime
Entre nous c'est fini
Je sens que je vais regretter mon déjeuner au lit
Tous ses bons petits plats et bien d'autres choses aussi
On dit "Une de perdue pour dix de retrouvées"
Alors n'en parlons plus, oh oui, cette fois c'est terminé
272
{'artist': 'Dick Rivers', 'duree': '', 'genre': '', 'name': 'Si Un Jour', 'style': 'Rock'}
Si un jour
Oh, si un jour tu me revenais
Sans te l'avoir demandé j’offrirais
Tous mes jours
Sans espoir, sans amour
Oh, oh, si un jour
Tu me revenais
Si un jour
Oh, si un jour tu me revenais
Comme par le temps passé
Ils fuirai

Je me ferai, je me ferai, je me ferai belle
{au Refrain}
283
{'artist': 'AMIR', 'duree': '', 'genre': '', 'name': 'LONGTEMPS', 'style': 'VF'}

J'veux des problèmes
J'veux qu'tes galères deviennent les miennes
J'veux qu'tu m'balances au visage tes orages tes peines
Pour des nuits diluviennes

J'veux qu'on s'apprenne
J'veux partager tes joies, tes migraines
Ton corps me donne le vertige et tes mains me mènent
Où rien ne nous gêne

J'pourrais m'tatouer notre histoire sur le bras
Me mettre dans de beaux draps si t'es avec moi
C'est toi dans ce monde de fous
Je l'sais c'est tout

Et j'voudrais qu'ça dure longtemps
User ma peau sur la tienne
Un jour j'oublierai tout jusqu'à mon nom je saurai simplement
Que t'es là que t'es belle que t'es mienne

J'voudrais qu'ça dure 100 ans
Que jamais la raison n'atteigne
Cet aveu cette envie de rêver tous les deux quand même
Jusqu'à ce qu'un jour nos deux yeux s'éteignent

Mon évidence, t'es mon sourire et ma carte chance
J'veux qu'on déconne qu'on décolle

Ta sensualité
290
{'artist': 'DE PALMAS', 'duree': '', 'genre': '', 'name': 'SUR LA ROUTE', 'style': 'VF'}
291
{'artist': 'LOUANE', 'duree': '', 'genre': '', 'name': "SI T'ETAIS LA", 'style': 'VF'}

Parfois, je pense à toi dans les voitures
Le pire, c'est les voyages, c'est d'aventure
Une chanson fait revivre un souvenir
Les questions sans réponse, ça c'est le pire

Est-ce que tu m'entends ? Est-ce que tu me vois ?
Qu'est-ce que tu dirais, toi, si t'étais là ?
Est-ce que ce sont des signes que tu m'envoies ?
Qu'est-ce que tu ferais, toi, si t'étais là ?

J'me raconte des histoires pour m'endormir
Pour endormir ma peine et pour sourire
J'ai des conversations imaginaires
Avec des gens qui ne sont pas sur la terre

Est-ce que tu m'entends ? Est-ce que tu me vois ?
Qu'est-ce que tu dirais, toi, si t'étais là ?
Est-ce que ce sont des signes que tu m'envoies ?
Qu'est-ce que tu ferais, toi, si t'étais là ?
292
{'artist': 'EDDY MITCHELL', 'duree': '', 'genre': '', 'name': "COULEUR MENTHE A L'E

L'оle aux oiseaux
Je suis tombй pour elle
Je n'ai d'yeux que pour elle
Ma maison, ma Tour Eiffel
Quand mes amours prennent l'eau
L'оle aux oiseaux
298
{'artist': 'Renaud', 'duree': '', 'genre': '', 'name': 'Mistral gagnant', 'style': 'VF'}
Intéressé(e) par l'explication des paroles de cette chanson ou d'autres ? Venez faire l'analyse des textes avec nous !
A m'asseoir sur un banc cinq minutes avec toi
Et regarder les gens tant qu'y en a
Te parler du bon temps qu'est mort ou qui r'viendra
En serrant dans ma main tes p'tits doigts
Pis donner à bouffer à des pigeons idiots
Leur filer des coups d' pieds pour de faux
Et entendre ton rire qui lézarde les murs
Qui sait surtout guérir mes blessures
Te raconter un peu
Comment j'étais mino
Les bonbecs fabuleux
Qu'on piquait chez l' marchand
Car-en-sac et Minto
Caramel à un franc
Et les mistrals gagnants
A r'marcher sous la pluie cinq minutes avec toi
Et regarder la vie tant qu'y en a
Te raconter la Terre en te bouffant des yeux
Te parler de ta m

La mer c'est son malheur

Dès que le vent soufflera
Je repartira
Dès que les vents tourneront
Nous nous en allerons

C'est pas l'homme qui prend la mer
C'est la mer qui prend l'homme
Moi la mer elle m'a pris
Comme on prend un taxi
Je f'rai le tour du monde
Pour voir à chaque étape
Si tous les gars du monde
Veulent bien m'lâcher la grappe
J'irais aux quatre vents
Foutre un peu le boxon
Jamais les océans
N'oublieront mon prénom

Dès que le vent soufflera
Je repartira
Dès que les vents tourneront
Nous nous en allerons

Ho ho ho ho ho hissez haut ho ho ho

C'est pas l'homme qui prend la mer
C'est la mer qui prend l'homme
Moi la mer elle m'a pris
Et mon bateau aussi
Il est fier mon navire
Il est est beau mon bateau
C'est un fameux trois-mâts
Fin comme un oiseau (Hissez haut)
Tabarly, Pajot
Kersauson et Riguidel
Naviguent pas sur des cageots
Ni sur des poubelles
306
{'artist': 'Renaud', 'duree': '', 'genre': '', 'name': 'Manhattan Kaboul', 'style': 'VF'}

Petit portoricain, bien intégré quas

In [43]:
song_data = pd.read_csv('Corpus_file.csv') 
song_style = song_data["Style"].tolist()[:len(corpus_list)]

In [58]:
len(music_style)

315

In [6]:
# Telecharge le modele StanfordNLP en Français
# Peut prendre un peu de temps



#stanfordnlp.download('fr')

In [293]:
nlp = stanfordnlp.Pipeline(lang="fr",processors='tokenize,pos,lemma')

Use device: gpu
---
Loading: tokenize
With settings: 
{'model_path': 'C:\\Users\\sylva\\stanfordnlp_resources\\fr_gsd_models\\fr_gsd_tokenizer.pt', 'lang': 'fr', 'shorthand': 'fr_gsd', 'mode': 'predict'}
---
Loading: pos
With settings: 
{'model_path': 'C:\\Users\\sylva\\stanfordnlp_resources\\fr_gsd_models\\fr_gsd_tagger.pt', 'pretrain_path': 'C:\\Users\\sylva\\stanfordnlp_resources\\fr_gsd_models\\fr_gsd.pretrain.pt', 'lang': 'fr', 'shorthand': 'fr_gsd', 'mode': 'predict'}
---
Loading: lemma
With settings: 
{'model_path': 'C:\\Users\\sylva\\stanfordnlp_resources\\fr_gsd_models\\fr_gsd_lemmatizer.pt', 'lang': 'fr', 'shorthand': 'fr_gsd', 'mode': 'predict'}
Building an attentional Seq2Seq model...
Using a Bi-LSTM encoder
Using soft attention for LSTM.
Finetune all embeddings.
[Running seq2seq lemmatizer with edit classifier]
Done loading processors!
---


In [295]:
test = corpus_list[1]
doc = nlp(test)
for i in range(len(doc.sentences)):
    doc.sentences[i].print_tokens()

<Token index=1;words=[<Word index=1;text=Enfants;lemma=enfant;upos=NOUN;xpos=_;feats=Gender=Masc|Number=Plur>]>
<Token index=2;words=[<Word index=2;text=des;lemma=un;upos=DET;xpos=_;feats=Definite=Ind|Gender=Masc|Number=Plur|PronType=Art>]>
<Token index=3;words=[<Word index=3;text=parcs;lemma=parc;upos=NOUN;xpos=_;feats=Gender=Masc|Number=Plur>]>
<Token index=4;words=[<Word index=4;text=,;lemma=,;upos=PUNCT;xpos=_;feats=_>]>
<Token index=5;words=[<Word index=5;text=gamins;lemma=gamin;upos=NOUN;xpos=_;feats=Gender=Masc|Number=Plur>]>
<Token index=6;words=[<Word index=6;text=des;lemma=un;upos=DET;xpos=_;feats=Definite=Ind|Gender=Fem|Number=Plur|PronType=Art>]>
<Token index=7;words=[<Word index=7;text=plages;lemma=plage;upos=NOUN;xpos=_;feats=Gender=Fem|Number=Plur>]>
<Token index=8;words=[<Word index=8;text=Le;lemma=le;upos=DET;xpos=_;feats=Definite=Def|Gender=Masc|Number=Sing|PronType=Art>]>
<Token index=9;words=[<Word index=9;text=vent;lemma=vent;upos=NOUN;xpos=_;feats=Gender=Masc|Numb

<Token index=15;words=[<Word index=15;text=autrefois;lemma=autrefois;upos=ADV;xpos=_;feats=_>]>
<Token index=1;words=[<Word index=1;text=Au;lemma=Au;upos=ADP;xpos=_;feats=_>]>
<Token index=2;words=[<Word index=2;text=gré;lemma=gré;upos=NOUN;xpos=_;feats=Gender=Masc|Number=Sing>]>
<Token index=3;words=[<Word index=3;text=des;lemma=un;upos=DET;xpos=_;feats=Definite=Ind|Gender=Fem|Number=Plur|PronType=Art>]>
<Token index=4;words=[<Word index=4;text=saisons;lemma=saison;upos=NOUN;xpos=_;feats=Gender=Fem|Number=Plur>]>
<Token index=5;words=[<Word index=5;text=,;lemma=,;upos=PUNCT;xpos=_;feats=_>]>
<Token index=6;words=[<Word index=6;text=des;lemma=un;upos=DET;xpos=_;feats=Definite=Ind|Gender=Fem|Number=Plur|PronType=Art>]>
<Token index=7;words=[<Word index=7;text=décisions;lemma=décision;upos=NOUN;xpos=_;feats=Gender=Fem|Number=Plur>]>
<Token index=8;words=[<Word index=8;text=,;lemma=,;upos=PUNCT;xpos=_;feats=_>]>
<Token index=9;words=[<Word index=9;text=je;lemma=il;upos=PRON;xpos=_;feats=N

In [319]:
import pandas as pd

#extract lemma
def extract_lemma(doc):
    parsed_text = {'word':[], 'lemma':[]}
    for sent in doc.sentences:
        for wrd in sent.words:
            #extract text and lemma
            parsed_text['word'].append(wrd.text)
            parsed_text['lemma'].append(wrd.lemma)
    #return a dataframe
    #pd.DataFrame(parsed_text)
    return  parsed_text

#call the function on doc
lemma = extract_lemma(doc)

In [321]:
lemma['lemma']

['bien',
 'sûr',
 ',',
 'nous',
 'eûme',
 'un',
 'orage',
 'Vingt',
 'an',
 'de',
 'amour',
 ',',
 'ce',
 'être',
 'le',
 'amour',
 'fol',
 'Mille',
 'fois',
 'il',
 'prendre',
 'son',
 'bagage',
 'Mille',
 'fois',
 'il',
 'prendre',
 'son',
 'envol',
 'et',
 'chaque',
 'meuble',
 'se',
 'souvenir',
 'dans',
 'ce',
 'chambre',
 'sans',
 'berceau',
 'un',
 'éclat',
 'un',
 'vieux',
 'tempête',
 'plus',
 'rien',
 'ne',
 'ressembler',
 'à',
 'rien',
 'il',
 'avoir',
 'perdre',
 'le',
 'goût',
 'de',
 'le',
 'eau',
 'et',
 'soi',
 'celui',
 'de',
 'le',
 'conquête',
 'mais',
 'son',
 'amour',
 'son',
 'doux',
 ',',
 'son',
 'tendre',
 ',',
 'son',
 'merveilleux',
 'amour',
 'de',
 'le',
 'aube',
 'clair',
 'jusque',
 'à',
 'le',
 'fin',
 'du',
 'jour',
 'il',
 'te',
 'aimer',
 'encore',
 ',',
 'il',
 'savoir',
 ',',
 'il',
 'te',
 'aimer',
 'soi',
 ',',
 'il',
 'savoir',
 'tout',
 'son',
 'sortilège',
 'il',
 'savoir',
 'tout',
 'son',
 'envoûtement',
 'il',
 'me',
 'avoir',
 'garder',
 'u

In [304]:
word_lemma = []
exclu_lemma = []
for i in range(len(corpus_list)):
    test = corpus_list[i]
    if len(test) > 0:
        doc = nlp(test)
        print(i)
        lemma = extract_lemma(doc)
        lemma2 = lemma['lemma']
        word_lemma.append(lemma2)
    else:
        exclu_lemma.append(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
61
62
63
64
65
66
67
68
69
70
71
74
75
76
77
79
80
81
82
84
85
86
88
89
90
92
93
94
95
96
97
98
99
100
101
102
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
136
137
138
139
140
141
142
143
144
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
194
195
198
199
200
202
204
205
206
210
213
215
216
217
218
220
221
222
224
225
227
230
232
233
234
236
237
238
240
241
242
243
244
245
246
248
249
250
251
252
253
254
255
256
257
258
259
261
262
263
264
265
266
267
268
269
270
271
272
273
275
276
277
278
280
281
282
283
284
285
286
287
288
289
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309

In [305]:
word_lemma

[['le',
  'sourire',
  'dehors',
  'à',
  'Angoulême',
  'un',
  'chasse-spleen',
  'Melchior',
  'Paris-Seychelles',
  'découvrir',
  'son',
  'corps',
  'depuis',
  'le',
  'scène',
  'du',
  'sombre',
  'décor',
  'Lucrèce',
  'être',
  'reine',
  'on',
  'se',
  'être',
  'dire',
  'un',
  'chose',
  'que',
  'le',
  'on',
  'ne',
  'tenir',
  'pas',
  'le',
  'temps',
  'que',
  'le',
  'eau',
  'se',
  'poser',
  'sur',
  'son',
  'ronce',
  'lila',
  'le',
  'soleil',
  'se',
  'endormir',
  'sur',
  'Seychelles',
  'le',
  'sable',
  'et',
  'le',
  'aurore',
  ',',
  'fleur',
  'de',
  'sel',
  'Attends',
  'soi',
  'il',
  'sor',
  ',',
  'de',
  'le',
  'Île',
  'aux',
  'cerf',
  'le',
  'orage',
  'être',
  'de',
  'le',
  'or',
  'pour',
  'se',
  'perdre',
  '(',
  'x4',
  ')',
  'I',
  'need',
  'you',
  'so',
  ',',
  'oh',
  'oh',
  'I',
  'won',
  "'t",
  'let',
  'you',
  'go',
  ',',
  'woh',
  'oh',
  'Souffrir',
  'le',
  'mort',
  'pour',
  'lui',
  'plaire',
  

In [9]:

def extract_pos(doc):
    parsed_text = {'word':[], 'upos':[]}
    for sent in doc.sentences:
        for wrd in sent.words:
           # if wrd.pos in pos_dict.keys():
               # pos_exp = pos_dict[wrd.upos]
            #else:
            #    pos_exp = 'NA'
            parsed_text['word'].append(wrd.text)
            parsed_text['upos'].append(wrd.upos)
            #parsed_text['exp'].append(pos_exp)
    #return a dataframe of pos and text
    return pd.DataFrame(parsed_text)

#extract pos
feature_word = extract_pos(doc)

In [133]:
corpus_list[79]

"Tout autour de nous les gens sont jaloux\nEt ne reprocher tout d'avoir pour toi des yeux trop doux\nDe t'aimer follement mon amour\nDe t'aimer follement nuit et jourCe n'est pas gentil mais ça m'est égale\nJe moque de ce qu'on dit car moi je trouve que c'est normal\nDe t'aimer follement mon amour\nDe t'aimer follement nuit et jourJe pense a chaque instant que tout peux m'arriver\nMais mon coeur ne peut changer il sera toujours vraiment content\nDe t'aimer follement mon amour\nDe t'aimer follement nuit et jourUn jour si tu veux on peut partir tous deux\nPartir en se moquant de ceux qui enrage en nous voyant\nDe nous aimer follement mon amour\nDe nous aimer follement nuit et jourA que la vie est douce quand on est amoureux\nUn rien vous rend heureux le ciel est plus bleu et tout me pousse\nA t'aimer follement mon amour\nA t'aimer follement nuit et jour ahMais quand tu n'est pas là je pense encore a toi\nCar je sais que tu reviendras et personne au monde ne m'empêchera\nDe t'aimer follem

In [138]:
ft_word = []
exclu = []

In [139]:
for i in range(len(corpus_list)):
    test = corpus_list[i]
    if len(test) > 0:
        doc = nlp(test)
        print(i)
        feature_word = extract_pos(doc)
        feature_word2 = feature_word["upos"].astype('category')
        ft_word.append(feature_word2.value_counts())
    else:
        exclu.append(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
61
62
63
64
65
66
67
68
69
70
71
74
75
76
77
79
80
81
82
84
85
86
88
89
90
92
93
94
95
96
97
98
99
100
101
102
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
136
137
138
139
140
141
142
143
144
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
194
195
198
199
200
202
204
205
206
210
213
215
216
217
218
220
221
222
224
225
227
230
232
233
234
236
237
238
240
241
242
243
244
245
246
248
249
250
251
252
253
254
255
256
257
258
259
261
262
263
264
265
266
267
268
269
270
271
272
273
275
276
277
278
280
281
282
283
284
285
286
287
288
289
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309

In [140]:
print(len(ft_word),len(exclu))


281 34


In [142]:
nb_word = []
for i in range(len(ft_word)):
    nb_word.append(ft_word[i].sum())

In [145]:
df = pd.DataFrame(ft_word)
df = df.set_index([pd.Index(list(range(len(df))))])
df = df.fillna(0)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 281 entries, 0 to 280
Data columns (total 17 columns):
ADJ      281 non-null float64
ADP      281 non-null float64
ADV      281 non-null float64
AUX      281 non-null float64
CCONJ    281 non-null float64
DET      281 non-null float64
INTJ     281 non-null float64
NOUN     281 non-null float64
NUM      281 non-null float64
PART     281 non-null float64
PRON     281 non-null float64
PROPN    281 non-null float64
PUNCT    281 non-null float64
SCONJ    281 non-null float64
SYM      281 non-null float64
VERB     281 non-null float64
X        281 non-null float64
dtypes: float64(17)
memory usage: 39.5 KB


In [146]:
df_freq = df.divide(nb_word, axis="index")
df_freq['nb_word'] = nb_word
df_freq.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 281 entries, 0 to 280
Data columns (total 18 columns):
ADJ        281 non-null float64
ADP        281 non-null float64
ADV        281 non-null float64
AUX        281 non-null float64
CCONJ      281 non-null float64
DET        281 non-null float64
INTJ       281 non-null float64
NOUN       281 non-null float64
NUM        281 non-null float64
PART       281 non-null float64
PRON       281 non-null float64
PROPN      281 non-null float64
PUNCT      281 non-null float64
SCONJ      281 non-null float64
SYM        281 non-null float64
VERB       281 non-null float64
X          281 non-null float64
nb_word    281 non-null int64
dtypes: float64(17), int64(1)
memory usage: 41.7 KB


In [227]:
print(*[f"index: {word.index.rjust(2)}\tword: {word.text.ljust(11)}\tgovernor index: {word.governor}\tgovernor: {(doc.sentences[0].words[word.governor-1].text if word.governor > 0 else 'root').ljust(11)}\tdeprel: {word.dependency_relation}" for word in doc.sentences[0].words], sep='\n')

TypeError: '>' not supported between instances of 'NoneType' and 'int'

-----------------------------------------------------------------
# Essai Modele

In [148]:
from nltk.corpus import stopwords 
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import nltk


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\sylva\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
nltk.download('stopwords')
stop_words = set(stopwords.words('french')) 

In [311]:
len(word_lemma)

281

In [307]:
corpus_list_clean = [corpus_list[i] for i in range(len(corpus_list)) if i not in exclu]
song_style_clean = [music_style[i] for i in range(len(corpus_list)) if i not in exclu]
print(len(corpus_list_clean))
print(len(song_style_clean))

281
281


In [309]:
corpus_list_clean = [word_lemma[i] for i in range(len(word_lemma)) if i not in exclu_lemma]
song_style_clean = [music_style[i] for i in range(len(word_lemma)) if i not in exclu_lemma]
print(len(corpus_list_clean))
print(len(song_style_clean))

248
281


In [280]:
count_vect = CountVectorizer( min_df=5, max_df=0.7, stop_words=stop_words)
df_count = count_vect.fit_transform(corpus_list_clean)
df_count

<281x796 sparse matrix of type '<class 'numpy.int64'>'
	with 11444 stored elements in Compressed Sparse Row format>

In [322]:
word_lemma2 = []
for i in range(len(word_lemma)):
    listToStr = ' '.join([str(elem) for elem in word_lemma[i]])
    word_lemma2.append(listToStr)

In [324]:
len(word_lemma2)

281

In [326]:
count_vect = CountVectorizer( min_df=5, max_df=0.7, stop_words=stop_words)
df_count = count_vect.fit_transform(word_lemma2)
df_count

<281x779 sparse matrix of type '<class 'numpy.int64'>'
	with 12454 stored elements in Compressed Sparse Row format>

In [327]:
tfidf_transformer = TfidfTransformer()
df_tfidf = tfidf_transformer.fit_transform(df_count)
df_tfidf.shape

(281, 779)

In [328]:
df_tfidf = pd.DataFrame(df_tfidf.A,columns=count_vect.get_feature_names())
df_tfidf.head()

20  abandonner  abord  adorer  affaire   ah  aider  aile  ailleurs  aime  \
0  0.0    0.000000    0.0     0.0      0.0  0.0    0.0   0.0       0.0   0.0   
1  0.0    0.476444    0.0     0.0      0.0  0.0    0.0   0.0       0.0   0.0   
2  0.0    0.000000    0.0     0.0      0.0  0.0    0.0   0.0       0.0   0.0   
3  0.0    0.000000    0.0     0.0      0.0  0.0    0.0   0.0       0.0   0.0   
4  0.0    0.096990    0.0     0.0      0.0  0.0    0.0   0.0       0.0   0.0   

   ...  écouter  écrire  élever  équipe  état  éternel  étoile  étonner  \
0  ...      0.0     0.0     0.0     0.0   0.0      0.0     0.0      0.0   
1  ...      0.0     0.0     0.0     0.0   0.0      0.0     0.0      0.0   
2  ...      0.0     0.0     0.0     0.0   0.0      0.0     0.0      0.0   
3  ...      0.0     0.0     0.0     0.0   0.0      0.0     0.0      0.0   
4  ...      0.0     0.0     0.0     0.0   0.0      0.0     0.0      0.0   

        île  œil  
0  0.157094  0.0  
1  0.000000  0.0  
2  0.000000  0.0  
3  0.000000  0.0  
4  0.000000  0.0  

[5 rows x 779 columns]

In [329]:
df_tot = pd.concat([df_tfidf, df_freq], axis=1, sort=False)
df_tot.head()

20  abandonner  abord  adorer  affaire   ah  aider  aile  ailleurs  aime  \
0  0.0    0.000000    0.0     0.0      0.0  0.0    0.0   0.0       0.0   0.0   
1  0.0    0.476444    0.0     0.0      0.0  0.0    0.0   0.0       0.0   0.0   
2  0.0    0.000000    0.0     0.0      0.0  0.0    0.0   0.0       0.0   0.0   
3  0.0    0.000000    0.0     0.0      0.0  0.0    0.0   0.0       0.0   0.0   
4  0.0    0.096990    0.0     0.0      0.0  0.0    0.0   0.0       0.0   0.0   

   ...       NUM  PART      PRON     PROPN     PUNCT     SCONJ       SYM  \
0  ...  0.000000   0.0  0.169935  0.052288  0.045752  0.013072  0.006536   
1  ...  0.000000   0.0  0.102564  0.035897  0.107692  0.015385  0.000000   
2  ...  0.035211   0.0  0.274648  0.014085  0.084507  0.035211  0.000000   
3  ...  0.006536   0.0  0.071895  0.117647  0.071895  0.000000  0.000000   
4  ...  0.000000   0.0  0.125490  0.007843  0.176471  0.007843  0.000000   

       VERB         X  nb_word  
0  0.117647  0.006536      153  
1  0.107692  0.000000      195  
2  0.112676  0.000000      142  
3  0.045752  0.000000      153  
4  0.172549  0.000000      255  

[5 rows x 797 columns]

In [330]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df3, song_style_clean, test_size=0.2, random_state=0)

In [331]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import SGDClassifier

# Random Forest

In [332]:
clf_rf = RandomForestClassifier(n_estimators=5000,random_state=0)
clf_rf.fit(X_train, y_train) 

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=5000,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [333]:
y_pred_rf = clf_rf.predict(X_test)
print(confusion_matrix(y_test,y_pred_rf))
print(classification_report(y_test,y_pred_rf))
print(accuracy_score(y_test, y_pred_rf))

[[ 0  0  0  5  0]
 [ 1  0  0  8  0]
 [ 0  3  7  3  0]
 [ 0  0  0 24  0]
 [ 0  0  0  6  0]]


C:\Users\sylva\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


              precision    recall  f1-score   support

        Jazz       0.00      0.00      0.00         5
         Pop       0.00      0.00      0.00         9
         Rap       1.00      0.54      0.70        13
        Rock       0.52      1.00      0.69        24
          VF       0.00      0.00      0.00         6

    accuracy                           0.54        57
   macro avg       0.30      0.31      0.28        57
weighted avg       0.45      0.54      0.45        57

0.543859649122807


# Multinomial

In [334]:
clf_multi = MultinomialNB()
clf_multi.fit(X_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [335]:
y_pred_multi = clf_multi.predict(X_test)
print(confusion_matrix(y_test,y_pred_multi))
print(classification_report(y_test,y_pred_multi))
print(accuracy_score(y_test, y_pred_multi))

[[ 0  0  1  4  0]
 [ 0  0  6  3  0]
 [ 0  0 12  1  0]
 [ 0  0  6 18  0]
 [ 0  0  5  1  0]]


C:\Users\sylva\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


              precision    recall  f1-score   support

        Jazz       0.00      0.00      0.00         5
         Pop       0.00      0.00      0.00         9
         Rap       0.40      0.92      0.56        13
        Rock       0.67      0.75      0.71        24
          VF       0.00      0.00      0.00         6

    accuracy                           0.53        57
   macro avg       0.21      0.33      0.25        57
weighted avg       0.37      0.53      0.42        57

0.5263157894736842


# SVM

In [336]:
from sklearn.svm import SVC
tuned_parameters = [{'kernel': ['rbf'], 'gamma': [1e-3, 1e-4],
                     'C': [1, 10, 100, 1000]},
                    {'kernel': ['linear'], 'C': [1, 10, 100, 1000]}]
clf_svc = GridSearchCV(
        SVC(), tuned_parameters, scoring='f1_micro'
    )
clf_svc.fit(X_train, y_train)

C:\Users\sylva\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\sylva\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid=[{'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001],
                          'kernel': ['rbf']},
                         {'C': [1, 10, 100, 1000], 'kernel': ['linear']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='f1_micro', verbose=0)

In [338]:
y_pred_svc = clf_svc.predict(X_test)
print(confusion_matrix(y_test,y_pred_svc))
print(classification_report(y_test,y_pred_svc))
print(accuracy_score(y_test, y_pred_svc))

[[ 0  1  0  4  0]
 [ 0  3  0  6  0]
 [ 0  2  9  2  0]
 [ 0  0  0 24  0]
 [ 0  2  0  2  2]]


C:\Users\sylva\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


              precision    recall  f1-score   support

        Jazz       0.00      0.00      0.00         5
         Pop       0.38      0.33      0.35         9
         Rap       1.00      0.69      0.82        13
        Rock       0.63      1.00      0.77        24
          VF       1.00      0.33      0.50         6

    accuracy                           0.67        57
   macro avg       0.60      0.47      0.49        57
weighted avg       0.66      0.67      0.62        57

0.6666666666666666


In [220]:
from sklearn.ensemble import GradientBoostingClassifier

In [228]:
clf_gb = GradientBoostingClassifier(n_estimators=1000,learning_rate=0.01)
clf_gb.fit(X_train,y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
                           learning_rate=0.01, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=1000,
                           n_iter_no_change=None, presort='auto',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [230]:
y_pred_gb = clf_gb.predict(X_test)
print(confusion_matrix(y_test,y_pred_svc))
print(classification_report(y_test,y_pred_svc))
print(accuracy_score(y_test, y_pred_svc))

[[ 1  1  0  3  0]
 [ 1  2  0  6  0]
 [ 0  1  9  2  1]
 [ 0  2  1 21  0]
 [ 0  3  0  3  0]]
              precision    recall  f1-score   support

        Jazz       0.50      0.20      0.29         5
         Pop       0.22      0.22      0.22         9
         Rap       0.90      0.69      0.78        13
        Rock       0.60      0.88      0.71        24
          VF       0.00      0.00      0.00         6

    accuracy                           0.58        57
   macro avg       0.44      0.40      0.40        57
weighted avg       0.54      0.58      0.54        57

0.5789473684210527


In [169]:
import pickle
# Save Model
with open('text_classifier', 'wb') as picklefile:
    pickle.dump(classifier,picklefile)

In [55]:
# Load model
with open('text_classifier', 'rb') as training_model:
    model = pickle.load(training_model)